#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    vimcompatible = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    filemanager = "nerdtree"
    enable_vimfiler_gitstatus = true
    filetree_direction = "left"
    relativenumber = false

    disabled_plugins = ["vim-surround"]
    git_plugin = 'fugitive'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "lsp"
  filetypes = [
    "javascript",
    "ruby",
    "rust"
  ]
  [layers.override_cmd]
    ocalm = ["reason-language-server"]
    ruby = ["solargraph", "stdio"]


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "fzf"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#haskell"

[[layers]]
name = "lang#rust"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
name = "test"

# reason ml layer
[[custom_plugins]]
   name = "reasonml-editor/vim-reason-plus"
   # note: you need to disable merged feature
   merged = false

# vim nix
[[custom_plugins]]
   name = "LnL7/vim-nix"
   # note: you need to disable merged feature
   merged = false
