xmodmap .Xmodmap
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 8 1
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 8 2
xinput set-int-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 8 6 7 4 5
export BROWSER=chromium
xrdb -merge ~/.Xdefaults
xrdb -merge ~/.Xresources
setxkbmap -option ctrl:nocaps

#xrdb -load /home/tha/.Xresources
#/home/tha/.dropbox-dist/dropbox &
#/usr/local/bin/dropbox.py start

/usr/local/bin/xflux -l 43.654692 -g -79.418367
eval `ssh-agent`
ssh-add
exec /usr/local/bin/wmii -r /home/tha/.wmii/wmiirc
#exec /usr/bin/enlightenment_start
